version: "3"

volumes:
  log-data:

services:
  app:
    build: ./app
    volumes:
      - log-data:/applog
  fluentd-send:
    build: ./fluentd-send
    environment:
      - FLUENT_FOWARD_TO=fluentd-recv
    volumes:
      - log-data:/applog
  fluentd-recv:
    image: fluent/fluentd
